# Generated by Django 6.0.5 on 2026-05-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Đường dẫn URL (vd: data-visualization)", unique=True
                    ),
                ),
                ("short_description", models.TextField(max_length=250)),
                ("detail_content", models.TextField()),
            ],
        ),
    ]
