# Generated by Django 6.0.5 on 2026-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="detail_content",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="name",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="short_description",
        ),
        migrations.AddField(
            model_name="skill",
            name="detail_content_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nội dung chi tiết (EN)"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="detail_content_vi",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nội dung chi tiết (VI)"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tên (EN)"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_vi",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tên (VI)"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="short_description_en",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Mô tả ngắn (EN)"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="short_description_vi",
            field=models.TextField(
                blank=True, max_length=250, null=True, verbose_name="Mô tả ngắn (VI)"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="slug",
            field=models.SlugField(
                help_text="Dùng để tạo link, ví dụ: 'data-modeling'", unique=True
            ),
        ),
    ]
