# Generated by Django 6.0.5 on 2026-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_skill_detail_content_remove_skill_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Cấu hình trang chủ", max_length=100),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "image_position",
                    models.CharField(
                        choices=[
                            ("right", "Bên phải (Mặc định)"),
                            ("left", "Bên trái"),
                        ],
                        default="right",
                        max_length=10,
                        verbose_name="Vị trí hiển thị ảnh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấu hình Trang Chủ",
                "verbose_name_plural": "Cấu hình Trang Chủ",
            },
        ),
    ]
