# Generated by Django 6.0.5 on 2026-05-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_delete_homepageconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
