# Generated by Django 6.0.5 on 2026-06-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_name", models.CharField(default="home", max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(default="Không rõ", max_length=100)),
                ("region", models.CharField(default="Không rõ", max_length=100)),
                ("isp", models.CharField(default="Không rõ", max_length=255)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
